version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29@sha256:92328e25353eb1e6fb542ffd9a32aee5cdc5309e1732458e2c47e87538a40048
    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "/usr/share/zoneinfo/Asia/Seoul"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "dependencies.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "dependencies.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint check coverageReport mergeCoverageReports --console=plain
      - run:
          name: Upload Code Coverage Report to codecov
          command: bash <(curl -s https://codecov.io/bash)
